// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicPacket.proto

#include "LogicPacket.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace User {

inline constexpr S2CPCLoginUserRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userid_{0u},
        userlevel_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S2CPCLoginUserRes::S2CPCLoginUserRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct S2CPCLoginUserResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2CPCLoginUserResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2CPCLoginUserResDefaultTypeInternal() {}
  union {
    S2CPCLoginUserRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2CPCLoginUserResDefaultTypeInternal _S2CPCLoginUserRes_default_instance_;

inline constexpr C2SPCLoginUserReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR C2SPCLoginUserReq::C2SPCLoginUserReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct C2SPCLoginUserReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2SPCLoginUserReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2SPCLoginUserReqDefaultTypeInternal() {}
  union {
    C2SPCLoginUserReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2SPCLoginUserReqDefaultTypeInternal _C2SPCLoginUserReq_default_instance_;

inline constexpr PacketType::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : Type_oneof_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR PacketType::PacketType(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PacketTypeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketTypeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketTypeDefaultTypeInternal() {}
  union {
    PacketType _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketTypeDefaultTypeInternal _PacketType_default_instance_;
}  // namespace User
static ::_pb::Metadata file_level_metadata_LogicPacket_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_LogicPacket_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_LogicPacket_2eproto = nullptr;
const ::uint32_t TableStruct_LogicPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::User::PacketType, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::User::PacketType, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::User::PacketType, _impl_.Type_oneof_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::User::C2SPCLoginUserReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::User::C2SPCLoginUserReq, _impl_.userid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::User::S2CPCLoginUserRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::User::S2CPCLoginUserRes, _impl_.userid_),
    PROTOBUF_FIELD_OFFSET(::User::S2CPCLoginUserRes, _impl_.username_),
    PROTOBUF_FIELD_OFFSET(::User::S2CPCLoginUserRes, _impl_.userlevel_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::User::PacketType)},
        {11, -1, -1, sizeof(::User::C2SPCLoginUserReq)},
        {20, -1, -1, sizeof(::User::S2CPCLoginUserRes)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::User::_PacketType_default_instance_._instance,
    &::User::_C2SPCLoginUserReq_default_instance_._instance,
    &::User::_S2CPCLoginUserRes_default_instance_._instance,
};
const char descriptor_table_protodef_LogicPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021LogicPacket.proto\022\004User\"\202\001\n\nPacketType"
    "\0222\n\017C2SLoginUserReq\030\001 \001(\0132\027.User.C2SPCLo"
    "ginUserReqH\000\0222\n\017S2CLoginUserRes\030\002 \001(\0132\027."
    "User.S2CPCLoginUserResH\000B\014\n\nType_oneof\"#"
    "\n\021C2SPCLoginUserReq\022\016\n\006UserID\030\001 \001(\r\"H\n\021S"
    "2CPCLoginUserRes\022\016\n\006UserID\030\001 \001(\r\022\020\n\010User"
    "Name\030\002 \001(\t\022\021\n\tUserLevel\030\003 \001(\rb\006proto3"
};
static ::absl::once_flag descriptor_table_LogicPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_LogicPacket_2eproto = {
    false,
    false,
    277,
    descriptor_table_protodef_LogicPacket_2eproto,
    "LogicPacket.proto",
    &descriptor_table_LogicPacket_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_LogicPacket_2eproto::offsets,
    file_level_metadata_LogicPacket_2eproto,
    file_level_enum_descriptors_LogicPacket_2eproto,
    file_level_service_descriptors_LogicPacket_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_LogicPacket_2eproto_getter() {
  return &descriptor_table_LogicPacket_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_LogicPacket_2eproto(&descriptor_table_LogicPacket_2eproto);
namespace User {
// ===================================================================

class PacketType::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::User::PacketType, _impl_._oneof_case_);
  static const ::User::C2SPCLoginUserReq& c2sloginuserreq(const PacketType* msg);
  static const ::User::S2CPCLoginUserRes& s2cloginuserres(const PacketType* msg);
};

const ::User::C2SPCLoginUserReq& PacketType::_Internal::c2sloginuserreq(const PacketType* msg) {
  return *msg->_impl_.Type_oneof_.c2sloginuserreq_;
}
const ::User::S2CPCLoginUserRes& PacketType::_Internal::s2cloginuserres(const PacketType* msg) {
  return *msg->_impl_.Type_oneof_.s2cloginuserres_;
}
void PacketType::set_allocated_c2sloginuserreq(::User::C2SPCLoginUserReq* c2sloginuserreq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Type_oneof();
  if (c2sloginuserreq) {
    ::google::protobuf::Arena* submessage_arena = c2sloginuserreq->GetArena();
    if (message_arena != submessage_arena) {
      c2sloginuserreq = ::google::protobuf::internal::GetOwnedMessage(message_arena, c2sloginuserreq, submessage_arena);
    }
    set_has_c2sloginuserreq();
    _impl_.Type_oneof_.c2sloginuserreq_ = c2sloginuserreq;
  }
  // @@protoc_insertion_point(field_set_allocated:User.PacketType.C2SLoginUserReq)
}
void PacketType::set_allocated_s2cloginuserres(::User::S2CPCLoginUserRes* s2cloginuserres) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Type_oneof();
  if (s2cloginuserres) {
    ::google::protobuf::Arena* submessage_arena = s2cloginuserres->GetArena();
    if (message_arena != submessage_arena) {
      s2cloginuserres = ::google::protobuf::internal::GetOwnedMessage(message_arena, s2cloginuserres, submessage_arena);
    }
    set_has_s2cloginuserres();
    _impl_.Type_oneof_.s2cloginuserres_ = s2cloginuserres;
  }
  // @@protoc_insertion_point(field_set_allocated:User.PacketType.S2CLoginUserRes)
}
PacketType::PacketType(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:User.PacketType)
}
inline PROTOBUF_NDEBUG_INLINE PacketType::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : Type_oneof_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

PacketType::PacketType(
    ::google::protobuf::Arena* arena,
    const PacketType& from)
    : ::google::protobuf::Message(arena) {
  PacketType* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (Type_oneof_case()) {
    case TYPE_ONEOF_NOT_SET:
      break;
      case kC2SLoginUserReq:
        _impl_.Type_oneof_.c2sloginuserreq_ = CreateMaybeMessage<::User::C2SPCLoginUserReq>(arena, *from._impl_.Type_oneof_.c2sloginuserreq_);
        break;
      case kS2CLoginUserRes:
        _impl_.Type_oneof_.s2cloginuserres_ = CreateMaybeMessage<::User::S2CPCLoginUserRes>(arena, *from._impl_.Type_oneof_.s2cloginuserres_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:User.PacketType)
}
inline PROTOBUF_NDEBUG_INLINE PacketType::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : Type_oneof_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void PacketType::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PacketType::~PacketType() {
  // @@protoc_insertion_point(destructor:User.PacketType)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PacketType::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_Type_oneof()) {
    clear_Type_oneof();
  }
  _impl_.~Impl_();
}

void PacketType::clear_Type_oneof() {
// @@protoc_insertion_point(one_of_clear_start:User.PacketType)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (Type_oneof_case()) {
    case kC2SLoginUserReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Type_oneof_.c2sloginuserreq_;
      }
      break;
    }
    case kS2CLoginUserRes: {
      if (GetArena() == nullptr) {
        delete _impl_.Type_oneof_.s2cloginuserres_;
      }
      break;
    }
    case TYPE_ONEOF_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = TYPE_ONEOF_NOT_SET;
}


PROTOBUF_NOINLINE void PacketType::Clear() {
// @@protoc_insertion_point(message_clear_start:User.PacketType)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_Type_oneof();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PacketType::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> PacketType::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PacketType_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .User.C2SPCLoginUserReq C2SLoginUserReq = 1;
    {PROTOBUF_FIELD_OFFSET(PacketType, _impl_.Type_oneof_.c2sloginuserreq_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .User.S2CPCLoginUserRes S2CLoginUserRes = 2;
    {PROTOBUF_FIELD_OFFSET(PacketType, _impl_.Type_oneof_.s2cloginuserres_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::User::C2SPCLoginUserReq>()},
    {::_pbi::TcParser::GetTable<::User::S2CPCLoginUserRes>()},
  }}, {{
  }},
};

::uint8_t* PacketType::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:User.PacketType)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (Type_oneof_case()) {
    case kC2SLoginUserReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, _Internal::c2sloginuserreq(this),
          _Internal::c2sloginuserreq(this).GetCachedSize(), target, stream);
      break;
    }
    case kS2CLoginUserRes: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, _Internal::s2cloginuserres(this),
          _Internal::s2cloginuserres(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:User.PacketType)
  return target;
}

::size_t PacketType::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:User.PacketType)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (Type_oneof_case()) {
    // .User.C2SPCLoginUserReq C2SLoginUserReq = 1;
    case kC2SLoginUserReq: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.Type_oneof_.c2sloginuserreq_);
      break;
    }
    // .User.S2CPCLoginUserRes S2CLoginUserRes = 2;
    case kS2CLoginUserRes: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.Type_oneof_.s2cloginuserres_);
      break;
    }
    case TYPE_ONEOF_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PacketType::_class_data_ = {
    PacketType::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PacketType::GetClassData() const {
  return &_class_data_;
}

void PacketType::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PacketType*>(&to_msg);
  auto& from = static_cast<const PacketType&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:User.PacketType)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.Type_oneof_case()) {
    case kC2SLoginUserReq: {
      _this->_internal_mutable_c2sloginuserreq()->::User::C2SPCLoginUserReq::MergeFrom(
          from._internal_c2sloginuserreq());
      break;
    }
    case kS2CLoginUserRes: {
      _this->_internal_mutable_s2cloginuserres()->::User::S2CPCLoginUserRes::MergeFrom(
          from._internal_s2cloginuserres());
      break;
    }
    case TYPE_ONEOF_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PacketType::CopyFrom(const PacketType& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:User.PacketType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PacketType::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PacketType::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PacketType::InternalSwap(PacketType* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.Type_oneof_, other->_impl_.Type_oneof_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata PacketType::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LogicPacket_2eproto_getter, &descriptor_table_LogicPacket_2eproto_once,
      file_level_metadata_LogicPacket_2eproto[0]);
}
// ===================================================================

class C2SPCLoginUserReq::_Internal {
 public:
};

C2SPCLoginUserReq::C2SPCLoginUserReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:User.C2SPCLoginUserReq)
}
C2SPCLoginUserReq::C2SPCLoginUserReq(
    ::google::protobuf::Arena* arena, const C2SPCLoginUserReq& from)
    : C2SPCLoginUserReq(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE C2SPCLoginUserReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void C2SPCLoginUserReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.userid_ = {};
}
C2SPCLoginUserReq::~C2SPCLoginUserReq() {
  // @@protoc_insertion_point(destructor:User.C2SPCLoginUserReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void C2SPCLoginUserReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void C2SPCLoginUserReq::Clear() {
// @@protoc_insertion_point(message_clear_start:User.C2SPCLoginUserReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* C2SPCLoginUserReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> C2SPCLoginUserReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_C2SPCLoginUserReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint32 UserID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(C2SPCLoginUserReq, _impl_.userid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(C2SPCLoginUserReq, _impl_.userid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 UserID = 1;
    {PROTOBUF_FIELD_OFFSET(C2SPCLoginUserReq, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* C2SPCLoginUserReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:User.C2SPCLoginUserReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 UserID = 1;
  if (this->_internal_userid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_userid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:User.C2SPCLoginUserReq)
  return target;
}

::size_t C2SPCLoginUserReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:User.C2SPCLoginUserReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 UserID = 1;
  if (this->_internal_userid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_userid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData C2SPCLoginUserReq::_class_data_ = {
    C2SPCLoginUserReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* C2SPCLoginUserReq::GetClassData() const {
  return &_class_data_;
}

void C2SPCLoginUserReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<C2SPCLoginUserReq*>(&to_msg);
  auto& from = static_cast<const C2SPCLoginUserReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:User.C2SPCLoginUserReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_userid() != 0) {
    _this->_internal_set_userid(from._internal_userid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void C2SPCLoginUserReq::CopyFrom(const C2SPCLoginUserReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:User.C2SPCLoginUserReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool C2SPCLoginUserReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* C2SPCLoginUserReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void C2SPCLoginUserReq::InternalSwap(C2SPCLoginUserReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.userid_, other->_impl_.userid_);
}

::google::protobuf::Metadata C2SPCLoginUserReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LogicPacket_2eproto_getter, &descriptor_table_LogicPacket_2eproto_once,
      file_level_metadata_LogicPacket_2eproto[1]);
}
// ===================================================================

class S2CPCLoginUserRes::_Internal {
 public:
};

S2CPCLoginUserRes::S2CPCLoginUserRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:User.S2CPCLoginUserRes)
}
inline PROTOBUF_NDEBUG_INLINE S2CPCLoginUserRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : username_(arena, from.username_),
        _cached_size_{0} {}

S2CPCLoginUserRes::S2CPCLoginUserRes(
    ::google::protobuf::Arena* arena,
    const S2CPCLoginUserRes& from)
    : ::google::protobuf::Message(arena) {
  S2CPCLoginUserRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, userid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, userid_),
           offsetof(Impl_, userlevel_) -
               offsetof(Impl_, userid_) +
               sizeof(Impl_::userlevel_));

  // @@protoc_insertion_point(copy_constructor:User.S2CPCLoginUserRes)
}
inline PROTOBUF_NDEBUG_INLINE S2CPCLoginUserRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : username_(arena),
        _cached_size_{0} {}

inline void S2CPCLoginUserRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, userid_),
           0,
           offsetof(Impl_, userlevel_) -
               offsetof(Impl_, userid_) +
               sizeof(Impl_::userlevel_));
}
S2CPCLoginUserRes::~S2CPCLoginUserRes() {
  // @@protoc_insertion_point(destructor:User.S2CPCLoginUserRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void S2CPCLoginUserRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.username_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void S2CPCLoginUserRes::Clear() {
// @@protoc_insertion_point(message_clear_start:User.S2CPCLoginUserRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.username_.ClearToEmpty();
  ::memset(&_impl_.userid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.userlevel_) -
      reinterpret_cast<char*>(&_impl_.userid_)) + sizeof(_impl_.userlevel_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* S2CPCLoginUserRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 39, 2> S2CPCLoginUserRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_S2CPCLoginUserRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 UserID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S2CPCLoginUserRes, _impl_.userid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S2CPCLoginUserRes, _impl_.userid_)}},
    // string UserName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(S2CPCLoginUserRes, _impl_.username_)}},
    // uint32 UserLevel = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S2CPCLoginUserRes, _impl_.userlevel_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(S2CPCLoginUserRes, _impl_.userlevel_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 UserID = 1;
    {PROTOBUF_FIELD_OFFSET(S2CPCLoginUserRes, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string UserName = 2;
    {PROTOBUF_FIELD_OFFSET(S2CPCLoginUserRes, _impl_.username_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 UserLevel = 3;
    {PROTOBUF_FIELD_OFFSET(S2CPCLoginUserRes, _impl_.userlevel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\26\0\10\0\0\0\0\0"
    "User.S2CPCLoginUserRes"
    "UserName"
  }},
};

::uint8_t* S2CPCLoginUserRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:User.S2CPCLoginUserRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 UserID = 1;
  if (this->_internal_userid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_userid(), target);
  }

  // string UserName = 2;
  if (!this->_internal_username().empty()) {
    const std::string& _s = this->_internal_username();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "User.S2CPCLoginUserRes.UserName");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // uint32 UserLevel = 3;
  if (this->_internal_userlevel() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_userlevel(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:User.S2CPCLoginUserRes)
  return target;
}

::size_t S2CPCLoginUserRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:User.S2CPCLoginUserRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string UserName = 2;
  if (!this->_internal_username().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_username());
  }

  // uint32 UserID = 1;
  if (this->_internal_userid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_userid());
  }

  // uint32 UserLevel = 3;
  if (this->_internal_userlevel() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_userlevel());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData S2CPCLoginUserRes::_class_data_ = {
    S2CPCLoginUserRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* S2CPCLoginUserRes::GetClassData() const {
  return &_class_data_;
}

void S2CPCLoginUserRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<S2CPCLoginUserRes*>(&to_msg);
  auto& from = static_cast<const S2CPCLoginUserRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:User.S2CPCLoginUserRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  if (from._internal_userid() != 0) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (from._internal_userlevel() != 0) {
    _this->_internal_set_userlevel(from._internal_userlevel());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S2CPCLoginUserRes::CopyFrom(const S2CPCLoginUserRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:User.S2CPCLoginUserRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool S2CPCLoginUserRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* S2CPCLoginUserRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void S2CPCLoginUserRes::InternalSwap(S2CPCLoginUserRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S2CPCLoginUserRes, _impl_.userlevel_)
      + sizeof(S2CPCLoginUserRes::_impl_.userlevel_)
      - PROTOBUF_FIELD_OFFSET(S2CPCLoginUserRes, _impl_.userid_)>(
          reinterpret_cast<char*>(&_impl_.userid_),
          reinterpret_cast<char*>(&other->_impl_.userid_));
}

::google::protobuf::Metadata S2CPCLoginUserRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LogicPacket_2eproto_getter, &descriptor_table_LogicPacket_2eproto_once,
      file_level_metadata_LogicPacket_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace User
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
