// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: LogicPacket.proto

#include "LogicPacket.pb.h"
#include "LogicPacket.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace User {

static const char* ReqInfo_method_names[] = {
  "/User.ReqInfo/GetInfo",
};

std::unique_ptr< ReqInfo::Stub> ReqInfo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ReqInfo::Stub> stub(new ReqInfo::Stub(channel, options));
  return stub;
}

ReqInfo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetInfo_(ReqInfo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ReqInfo::Stub::GetInfo(::grpc::ClientContext* context, const ::User::C2STestInfoReq& request, ::User::S2CTestInfoRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::User::C2STestInfoReq, ::User::S2CTestInfoRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetInfo_, context, request, response);
}

void ReqInfo::Stub::async::GetInfo(::grpc::ClientContext* context, const ::User::C2STestInfoReq* request, ::User::S2CTestInfoRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::User::C2STestInfoReq, ::User::S2CTestInfoRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInfo_, context, request, response, std::move(f));
}

void ReqInfo::Stub::async::GetInfo(::grpc::ClientContext* context, const ::User::C2STestInfoReq* request, ::User::S2CTestInfoRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::User::S2CTestInfoRes>* ReqInfo::Stub::PrepareAsyncGetInfoRaw(::grpc::ClientContext* context, const ::User::C2STestInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::User::S2CTestInfoRes, ::User::C2STestInfoReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::User::S2CTestInfoRes>* ReqInfo::Stub::AsyncGetInfoRaw(::grpc::ClientContext* context, const ::User::C2STestInfoReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

ReqInfo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReqInfo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReqInfo::Service, ::User::C2STestInfoReq, ::User::S2CTestInfoRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ReqInfo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::User::C2STestInfoReq* req,
             ::User::S2CTestInfoRes* resp) {
               return service->GetInfo(ctx, req, resp);
             }, this)));
}

ReqInfo::Service::~Service() {
}

::grpc::Status ReqInfo::Service::GetInfo(::grpc::ServerContext* context, const ::User::C2STestInfoReq* request, ::User::S2CTestInfoRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace User

