// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicPacket.proto
// Protobuf C++ Version: 4.25.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_LogicPacket_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_LogicPacket_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_LogicPacket_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_LogicPacket_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_LogicPacket_2eproto;
namespace User {
class C2SPCLoginUserReq;
struct C2SPCLoginUserReqDefaultTypeInternal;
extern C2SPCLoginUserReqDefaultTypeInternal _C2SPCLoginUserReq_default_instance_;
class Default;
struct DefaultDefaultTypeInternal;
extern DefaultDefaultTypeInternal _Default_default_instance_;
class S2CPCLoginUserRes;
struct S2CPCLoginUserResDefaultTypeInternal;
extern S2CPCLoginUserResDefaultTypeInternal _S2CPCLoginUserRes_default_instance_;
}  // namespace User
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace User {
enum NUM : int {
  C2SLoginUserReq = 0,
  S2SLoginUserReq = 1,
  NUM_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  NUM_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool NUM_IsValid(int value);
extern const uint32_t NUM_internal_data_[];
constexpr NUM NUM_MIN = static_cast<NUM>(0);
constexpr NUM NUM_MAX = static_cast<NUM>(1);
constexpr int NUM_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
NUM_descriptor();
template <typename T>
const std::string& NUM_Name(T value) {
  static_assert(std::is_same<T, NUM>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to NUM_Name().");
  return NUM_Name(static_cast<NUM>(value));
}
template <>
inline const std::string& NUM_Name(NUM value) {
  return ::google::protobuf::internal::NameOfDenseEnum<NUM_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool NUM_Parse(absl::string_view name, NUM* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NUM>(
      NUM_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class S2CPCLoginUserRes final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:User.S2CPCLoginUserRes) */ {
 public:
  inline S2CPCLoginUserRes() : S2CPCLoginUserRes(nullptr) {}
  ~S2CPCLoginUserRes() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR S2CPCLoginUserRes(::google::protobuf::internal::ConstantInitialized);

  inline S2CPCLoginUserRes(const S2CPCLoginUserRes& from)
      : S2CPCLoginUserRes(nullptr, from) {}
  S2CPCLoginUserRes(S2CPCLoginUserRes&& from) noexcept
    : S2CPCLoginUserRes() {
    *this = ::std::move(from);
  }

  inline S2CPCLoginUserRes& operator=(const S2CPCLoginUserRes& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2CPCLoginUserRes& operator=(S2CPCLoginUserRes&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2CPCLoginUserRes& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2CPCLoginUserRes* internal_default_instance() {
    return reinterpret_cast<const S2CPCLoginUserRes*>(
               &_S2CPCLoginUserRes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(S2CPCLoginUserRes& a, S2CPCLoginUserRes& b) {
    a.Swap(&b);
  }
  inline void Swap(S2CPCLoginUserRes* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2CPCLoginUserRes* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2CPCLoginUserRes* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2CPCLoginUserRes>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S2CPCLoginUserRes& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const S2CPCLoginUserRes& from) {
    S2CPCLoginUserRes::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(S2CPCLoginUserRes* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "User.S2CPCLoginUserRes";
  }
  protected:
  explicit S2CPCLoginUserRes(::google::protobuf::Arena* arena);
  S2CPCLoginUserRes(::google::protobuf::Arena* arena, const S2CPCLoginUserRes& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserNameFieldNumber = 4,
    kSizeFieldNumber = 1,
    kTypeFieldNumber = 2,
    kUserIDFieldNumber = 3,
    kUserLevelFieldNumber = 5,
  };
  // string UserName = 4;
  void clear_username() ;
  const std::string& username() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_username(Arg_&& arg, Args_... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* value);

  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(
      const std::string& value);
  std::string* _internal_mutable_username();

  public:
  // uint32 Size = 1;
  void clear_size() ;
  ::uint32_t size() const;
  void set_size(::uint32_t value);

  private:
  ::uint32_t _internal_size() const;
  void _internal_set_size(::uint32_t value);

  public:
  // .User.NUM Type = 2;
  void clear_type() ;
  ::User::NUM type() const;
  void set_type(::User::NUM value);

  private:
  ::User::NUM _internal_type() const;
  void _internal_set_type(::User::NUM value);

  public:
  // uint32 UserID = 3;
  void clear_userid() ;
  ::uint32_t userid() const;
  void set_userid(::uint32_t value);

  private:
  ::uint32_t _internal_userid() const;
  void _internal_set_userid(::uint32_t value);

  public:
  // uint32 UserLevel = 5;
  void clear_userlevel() ;
  ::uint32_t userlevel() const;
  void set_userlevel(::uint32_t value);

  private:
  ::uint32_t _internal_userlevel() const;
  void _internal_set_userlevel(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:User.S2CPCLoginUserRes)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      39, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr username_;
    ::uint32_t size_;
    int type_;
    ::uint32_t userid_;
    ::uint32_t userlevel_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LogicPacket_2eproto;
};// -------------------------------------------------------------------

class Default final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:User.Default) */ {
 public:
  inline Default() : Default(nullptr) {}
  ~Default() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Default(::google::protobuf::internal::ConstantInitialized);

  inline Default(const Default& from)
      : Default(nullptr, from) {}
  Default(Default&& from) noexcept
    : Default() {
    *this = ::std::move(from);
  }

  inline Default& operator=(const Default& from) {
    CopyFrom(from);
    return *this;
  }
  inline Default& operator=(Default&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Default& default_instance() {
    return *internal_default_instance();
  }
  static inline const Default* internal_default_instance() {
    return reinterpret_cast<const Default*>(
               &_Default_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Default& a, Default& b) {
    a.Swap(&b);
  }
  inline void Swap(Default* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Default* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Default* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Default>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Default& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Default& from) {
    Default::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Default* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "User.Default";
  }
  protected:
  explicit Default(::google::protobuf::Arena* arena);
  Default(::google::protobuf::Arena* arena, const Default& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSizeFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // uint32 Size = 1;
  void clear_size() ;
  ::uint32_t size() const;
  void set_size(::uint32_t value);

  private:
  ::uint32_t _internal_size() const;
  void _internal_set_size(::uint32_t value);

  public:
  // .User.NUM Type = 2;
  void clear_type() ;
  ::User::NUM type() const;
  void set_type(::User::NUM value);

  private:
  ::User::NUM _internal_type() const;
  void _internal_set_type(::User::NUM value);

  public:
  // @@protoc_insertion_point(class_scope:User.Default)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::uint32_t size_;
    int type_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LogicPacket_2eproto;
};// -------------------------------------------------------------------

class C2SPCLoginUserReq final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:User.C2SPCLoginUserReq) */ {
 public:
  inline C2SPCLoginUserReq() : C2SPCLoginUserReq(nullptr) {}
  ~C2SPCLoginUserReq() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR C2SPCLoginUserReq(::google::protobuf::internal::ConstantInitialized);

  inline C2SPCLoginUserReq(const C2SPCLoginUserReq& from)
      : C2SPCLoginUserReq(nullptr, from) {}
  C2SPCLoginUserReq(C2SPCLoginUserReq&& from) noexcept
    : C2SPCLoginUserReq() {
    *this = ::std::move(from);
  }

  inline C2SPCLoginUserReq& operator=(const C2SPCLoginUserReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2SPCLoginUserReq& operator=(C2SPCLoginUserReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2SPCLoginUserReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2SPCLoginUserReq* internal_default_instance() {
    return reinterpret_cast<const C2SPCLoginUserReq*>(
               &_C2SPCLoginUserReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(C2SPCLoginUserReq& a, C2SPCLoginUserReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C2SPCLoginUserReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2SPCLoginUserReq* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2SPCLoginUserReq* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2SPCLoginUserReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C2SPCLoginUserReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const C2SPCLoginUserReq& from) {
    C2SPCLoginUserReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(C2SPCLoginUserReq* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "User.C2SPCLoginUserReq";
  }
  protected:
  explicit C2SPCLoginUserReq(::google::protobuf::Arena* arena);
  C2SPCLoginUserReq(::google::protobuf::Arena* arena, const C2SPCLoginUserReq& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSizeFieldNumber = 1,
    kTypeFieldNumber = 2,
    kUserIDFieldNumber = 3,
  };
  // uint32 Size = 1;
  void clear_size() ;
  ::uint32_t size() const;
  void set_size(::uint32_t value);

  private:
  ::uint32_t _internal_size() const;
  void _internal_set_size(::uint32_t value);

  public:
  // .User.NUM Type = 2;
  void clear_type() ;
  ::User::NUM type() const;
  void set_type(::User::NUM value);

  private:
  ::User::NUM _internal_type() const;
  void _internal_set_type(::User::NUM value);

  public:
  // uint32 UserID = 3;
  void clear_userid() ;
  ::uint32_t userid() const;
  void set_userid(::uint32_t value);

  private:
  ::uint32_t _internal_userid() const;
  void _internal_set_userid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:User.C2SPCLoginUserReq)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::uint32_t size_;
    int type_;
    ::uint32_t userid_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LogicPacket_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Default

// uint32 Size = 1;
inline void Default::clear_size() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.size_ = 0u;
}
inline ::uint32_t Default::size() const {
  // @@protoc_insertion_point(field_get:User.Default.Size)
  return _internal_size();
}
inline void Default::set_size(::uint32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:User.Default.Size)
}
inline ::uint32_t Default::_internal_size() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.size_;
}
inline void Default::_internal_set_size(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.size_ = value;
}

// .User.NUM Type = 2;
inline void Default::clear_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_ = 0;
}
inline ::User::NUM Default::type() const {
  // @@protoc_insertion_point(field_get:User.Default.Type)
  return _internal_type();
}
inline void Default::set_type(::User::NUM value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:User.Default.Type)
}
inline ::User::NUM Default::_internal_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::User::NUM>(_impl_.type_);
}
inline void Default::_internal_set_type(::User::NUM value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_ = value;
}

// -------------------------------------------------------------------

// C2SPCLoginUserReq

// uint32 Size = 1;
inline void C2SPCLoginUserReq::clear_size() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.size_ = 0u;
}
inline ::uint32_t C2SPCLoginUserReq::size() const {
  // @@protoc_insertion_point(field_get:User.C2SPCLoginUserReq.Size)
  return _internal_size();
}
inline void C2SPCLoginUserReq::set_size(::uint32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:User.C2SPCLoginUserReq.Size)
}
inline ::uint32_t C2SPCLoginUserReq::_internal_size() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.size_;
}
inline void C2SPCLoginUserReq::_internal_set_size(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.size_ = value;
}

// .User.NUM Type = 2;
inline void C2SPCLoginUserReq::clear_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_ = 0;
}
inline ::User::NUM C2SPCLoginUserReq::type() const {
  // @@protoc_insertion_point(field_get:User.C2SPCLoginUserReq.Type)
  return _internal_type();
}
inline void C2SPCLoginUserReq::set_type(::User::NUM value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:User.C2SPCLoginUserReq.Type)
}
inline ::User::NUM C2SPCLoginUserReq::_internal_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::User::NUM>(_impl_.type_);
}
inline void C2SPCLoginUserReq::_internal_set_type(::User::NUM value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_ = value;
}

// uint32 UserID = 3;
inline void C2SPCLoginUserReq::clear_userid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.userid_ = 0u;
}
inline ::uint32_t C2SPCLoginUserReq::userid() const {
  // @@protoc_insertion_point(field_get:User.C2SPCLoginUserReq.UserID)
  return _internal_userid();
}
inline void C2SPCLoginUserReq::set_userid(::uint32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:User.C2SPCLoginUserReq.UserID)
}
inline ::uint32_t C2SPCLoginUserReq::_internal_userid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.userid_;
}
inline void C2SPCLoginUserReq::_internal_set_userid(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.userid_ = value;
}

// -------------------------------------------------------------------

// S2CPCLoginUserRes

// uint32 Size = 1;
inline void S2CPCLoginUserRes::clear_size() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.size_ = 0u;
}
inline ::uint32_t S2CPCLoginUserRes::size() const {
  // @@protoc_insertion_point(field_get:User.S2CPCLoginUserRes.Size)
  return _internal_size();
}
inline void S2CPCLoginUserRes::set_size(::uint32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:User.S2CPCLoginUserRes.Size)
}
inline ::uint32_t S2CPCLoginUserRes::_internal_size() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.size_;
}
inline void S2CPCLoginUserRes::_internal_set_size(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.size_ = value;
}

// .User.NUM Type = 2;
inline void S2CPCLoginUserRes::clear_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_ = 0;
}
inline ::User::NUM S2CPCLoginUserRes::type() const {
  // @@protoc_insertion_point(field_get:User.S2CPCLoginUserRes.Type)
  return _internal_type();
}
inline void S2CPCLoginUserRes::set_type(::User::NUM value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:User.S2CPCLoginUserRes.Type)
}
inline ::User::NUM S2CPCLoginUserRes::_internal_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::User::NUM>(_impl_.type_);
}
inline void S2CPCLoginUserRes::_internal_set_type(::User::NUM value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_ = value;
}

// uint32 UserID = 3;
inline void S2CPCLoginUserRes::clear_userid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.userid_ = 0u;
}
inline ::uint32_t S2CPCLoginUserRes::userid() const {
  // @@protoc_insertion_point(field_get:User.S2CPCLoginUserRes.UserID)
  return _internal_userid();
}
inline void S2CPCLoginUserRes::set_userid(::uint32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:User.S2CPCLoginUserRes.UserID)
}
inline ::uint32_t S2CPCLoginUserRes::_internal_userid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.userid_;
}
inline void S2CPCLoginUserRes::_internal_set_userid(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.userid_ = value;
}

// string UserName = 4;
inline void S2CPCLoginUserRes::clear_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.username_.ClearToEmpty();
}
inline const std::string& S2CPCLoginUserRes::username() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:User.S2CPCLoginUserRes.UserName)
  return _internal_username();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void S2CPCLoginUserRes::set_username(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.username_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:User.S2CPCLoginUserRes.UserName)
}
inline std::string* S2CPCLoginUserRes::mutable_username() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:User.S2CPCLoginUserRes.UserName)
  return _s;
}
inline const std::string& S2CPCLoginUserRes::_internal_username() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.username_.Get();
}
inline void S2CPCLoginUserRes::_internal_set_username(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.username_.Set(value, GetArena());
}
inline std::string* S2CPCLoginUserRes::_internal_mutable_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.username_.Mutable( GetArena());
}
inline std::string* S2CPCLoginUserRes::release_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:User.S2CPCLoginUserRes.UserName)
  return _impl_.username_.Release();
}
inline void S2CPCLoginUserRes::set_allocated_username(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.username_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.username_.IsDefault()) {
          _impl_.username_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:User.S2CPCLoginUserRes.UserName)
}

// uint32 UserLevel = 5;
inline void S2CPCLoginUserRes::clear_userlevel() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.userlevel_ = 0u;
}
inline ::uint32_t S2CPCLoginUserRes::userlevel() const {
  // @@protoc_insertion_point(field_get:User.S2CPCLoginUserRes.UserLevel)
  return _internal_userlevel();
}
inline void S2CPCLoginUserRes::set_userlevel(::uint32_t value) {
  _internal_set_userlevel(value);
  // @@protoc_insertion_point(field_set:User.S2CPCLoginUserRes.UserLevel)
}
inline ::uint32_t S2CPCLoginUserRes::_internal_userlevel() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.userlevel_;
}
inline void S2CPCLoginUserRes::_internal_set_userlevel(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.userlevel_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace User


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::User::NUM> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::User::NUM>() {
  return ::User::NUM_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_LogicPacket_2eproto_2epb_2eh
